name: Deployment-Test

on:
    workflow_call:
        inputs:
            issue_number:
                required: true
                type: number

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    auto-fix:
        if: github.event_name == 'workflow_call' || github.event.label.name == 'deploy-test'
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set issue number and repo information
          run: |
              echo "ISSUE_NUMBER=${{ github.event.inputs.issue_number }}" >> $GITHUB_ENV
              echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
        
        - name: Send PR/Branch Info to Firebase
          run: |
            curl -X POST https://us-central1-pr-arena.cloudfunctions.net/api/receive-data \
            -H "Content-Type: application/json" \
            -d '{
            "repo": "${{ env.REPO_NAME }}",
            "issueNumber": "${{ env.ISSUE_NUMBER }}",
            }'

        - name: Post Webpage Link to GitHub Issue
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const issueNumber = ${{ env.ISSUE_NUMBER }};
              const firebaseWebpageURL = `https://pr-arena.web.app?issueNumber=${issueNumber}`;

              github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: `OpenHands has started processing this issue! You can view the proposed fixes and make a decision at [this link](${firebaseWebpageURL}).`
              });